# Generated by Django 6.0.4 on 2026-04-23 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="Libelle (ex: 'Siege')", max_length=120)),
                ('street_1', models.CharField(max_length=255)),
                ('street_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='Etat ou province')),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nom de la societe', max_length=255)),
                ('code', models.CharField(help_text='Code identifiant court', max_length=30, unique=True)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('street2', models.CharField(blank=True, max_length=255, verbose_name='Rue ligne 2')),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128, verbose_name='Etat ou province')),
                ('zip_code', models.CharField(blank=True, max_length=24)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hr/companies/logos/')),
                ('currency', models.CharField(default='XAF', help_text='Devise par defaut', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_company', models.ForeignKey(blank=True, help_text='Societe parente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
    ]
