# Generated by Django 6.0.4 on 2026-04-23 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='XAF', max_length=3)),
            ],
            options={
                'ordering': ['contract', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(help_text='Date of the service / intervention')),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost of the service', max_digits=18)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminé'), ('CANCELLED', 'Annulé')], default='NEW', max_length=15)),
                ('odometer_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Odometer value at time of service', max_digits=12, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='service_attachments/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['service', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Contract name / title', max_length=255)),
                ('reference', models.CharField(blank=True, help_text='External contract reference', max_length=100)),
                ('start_date', models.DateField(help_text='Date de début du contrat')),
                ('end_date', models.DateField(blank=True, help_text='Date de fin du contrat', null=True)),
                ('creation_date', models.DateField(blank=True, help_text='Date de création du contrat (when the contract was signed)', null=True)),
                ('activation_cost', models.DecimalField(decimal_places=2, default=0, help_text="One-time activation / setup cost (coûts d'activation)", max_digits=18)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=12)),
                ('terms', models.TextField(blank=True, help_text='Conditions générales: all information concerning the contract')),
                ('billing_period', models.ForeignKey(blank=True, help_text='Billing frequency: Mensuel, Trimestriel, Annuel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='config.period')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, help_text='Driver assigned to this contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='people.driver')),
                ('included_services', models.ManyToManyField(blank=True, help_text='Intervention types covered / included in this contract', related_name='included_in_contracts', to='config.interventiontype')),
                ('intervention_type', models.ForeignKey(help_text='Primary intervention type for this contract', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='config.interventiontype')),
                ('responsible', models.ForeignKey(blank=True, help_text='Internal person responsible for this contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_contracts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier / société associée providing this contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='people.supplier')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
