# Generated by Django 6.0.4 on 2026-04-23 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('operations', '0001_initial'),
        ('people', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='recurringcost',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_costs', to='operations.contract'),
        ),
        migrations.AddField(
            model_name='recurringcost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringcost',
            name='period',
            field=models.ForeignKey(help_text='Recurrence frequency for this cost', on_delete=django.db.models.deletion.PROTECT, to='config.period'),
        ),
        migrations.AddField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver at the time of the service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='people.driver'),
        ),
        migrations.AddField(
            model_name='service',
            name='intervention_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='config.interventiontype'),
        ),
        migrations.AddField(
            model_name='service',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='people.supplier'),
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='serviceattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceattachment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.service'),
        ),
    ]
