# Generated by Django 6.0.4 on 2026-04-23 09:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, help_text='Address or GPS coordinates', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_plate', models.CharField(help_text="Registration / plaque d'immatriculation. e.g. LT 1234 AB", max_length=20, unique=True)),
                ('vin', models.CharField(help_text='Vehicle Identification Number (numéro de châssis)', max_length=50, unique=True, verbose_name='VIN / Chassis Number')),
                ('order_date', models.DateField(blank=True, help_text='Date the vehicle was ordered', null=True)),
                ('registration_date', models.DateField(blank=True, help_text="Date d'immatriculation", null=True)),
                ('cancellation_date', models.DateField(blank=True, help_text='Date when the registration was cancelled/annulled', null=True)),
                ('first_contract_date', models.DateField(blank=True, help_text='Première date de contrat', null=True)),
                ('fiscal_horsepower', models.DecimalField(blank=True, decimal_places=2, help_text='Taxe sur la puissance (chevaux fiscaux)', max_digits=6, null=True)),
                ('catalog_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valeur catalogue TTC (toutes taxes comprises)', max_digits=18, null=True)),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, help_text="Valeur d'achat", max_digits=18, null=True)),
                ('residual_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valeur résiduelle estimée', max_digits=18, null=True)),
                ('state', models.CharField(choices=[('TO_ORDER', 'À commander'), ('NEW_REQUEST', 'Nouvelle demande'), ('REGISTERED', 'Inscrit'), ('DECOMMISSIONED', 'Déclassé')], default='NEW_REQUEST', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(help_text='Fleet category: Utilitaire, Berline, Bus, etc.', on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='config.vehiclecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, help_text='Currently assigned driver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='people.driver')),
                ('fleet_manager', models.ForeignKey(blank=True, help_text='Employee responsible for managing this vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_vehicles', to=settings.AUTH_USER_MODEL)),
                ('parking', models.ForeignKey(blank=True, help_text='Current parking / emplacement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.parking')),
                ('tags', models.ManyToManyField(blank=True, help_text='Labels / étiquettes for grouping and filtering', related_name='vehicles', to='config.tag')),
            ],
            options={
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='OdometerReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, help_text='Odometer value at reading time', max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(help_text='Distance unit: km or mi', on_delete=django.db.models.deletion.PROTECT, to='config.unit')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_readings', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['vehicle', '-date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(blank=True, help_text='Document reference / number', max_length=100)),
                ('issue_date', models.DateField(blank=True, help_text="Date d'émission", null=True)),
                ('expiry_date', models.DateField(blank=True, help_text="Date d'expiration. Required if the document type requires expiration.", null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='vehicle_documents/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif')], default='ACTIVE', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_documents', to='config.documenttype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['vehicle', 'document_type', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Standard 50 places, VIP 30 places', max_length=255)),
                ('total_seats', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=False, help_text='Only one layout per vehicle should be active at a time.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['vehicle', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_models/')),
                ('name', models.CharField(help_text='Model name. e.g. Hilux, Corolla, B8R', max_length=255)),
                ('model_year', models.PositiveSmallIntegerField(help_text='Year of the model (1970 to current year)', validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2027)])),
                ('seats', models.PositiveSmallIntegerField(blank=True, help_text='Number of seats', null=True)),
                ('doors', models.PositiveSmallIntegerField(blank=True, help_text='Number of doors', null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('has_tow_hitch', models.BooleanField(default=False, help_text='Whether the model has a tow hitch (attelage remorque)')),
                ('power', models.DecimalField(blank=True, decimal_places=2, help_text='Engine power value', max_digits=10, null=True)),
                ('range_value', models.DecimalField(blank=True, decimal_places=2, help_text='Range / plage (especially for electric vehicles)', max_digits=10, null=True)),
                ('co2_emission', models.DecimalField(blank=True, decimal_places=2, help_text='CO2 emission value', max_digits=10, null=True)),
                ('emission_standard', models.CharField(blank=True, help_text='Emission standard. e.g. Euro 6, Euro 5, Tier 4', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('emission_unit', models.ForeignKey(blank=True, help_text='Unit for CO2 emission. e.g. g/km', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_model_emission', to='config.unit')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_models', to='config.fueltype')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_models', to='people.manufacturer')),
                ('power_unit', models.ForeignKey(blank=True, help_text='Unit for power. e.g. ch, kW, hp', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_model_power', to='config.unit')),
                ('range_unit', models.ForeignKey(blank=True, help_text='Unit for range. e.g. km, mi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_model_range', to='config.unit')),
                ('suppliers', models.ManyToManyField(blank=True, help_text='Suppliers/dealers that can provide this model', related_name='vehicle_models', to='people.supplier')),
                ('traction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_models', to='config.tractiontype')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_models', to='config.transmission')),
                ('vehicle_type', models.ForeignKey(help_text='Physical type: Voiture, Bus, Camion, Moto, etc.', on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_models', to='config.vehicletype')),
            ],
            options={
                'ordering': ['manufacturer', 'name', '-model_year'],
                'unique_together': {('manufacturer', 'name', 'model_year')},
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehiclemodel'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_number', models.CharField(help_text='Seat identifier. e.g. A1, B3, 12', max_length=10)),
                ('row', models.PositiveSmallIntegerField()),
                ('column', models.PositiveSmallIntegerField()),
                ('seat_type', models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('DRIVER', 'Conducteur')], default='STANDARD', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='vehicles.vehiclelayout')),
            ],
            options={
                'ordering': ['layout', 'row', 'column'],
                'unique_together': {('layout', 'seat_number')},
            },
        ),
    ]
